//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accomtest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolestanDBEntities : DbContext
    {
        public GolestanDBEntities()
            : base("name=GolestanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalcLawTbl> CalcLawTbls { get; set; }
        public virtual DbSet<CalcRateCodeTbl> CalcRateCodeTbls { get; set; }
        public virtual DbSet<CalcRateTbl> CalcRateTbls { get; set; }
        public virtual DbSet<CalcTariffTbl> CalcTariffTbls { get; set; }
        public virtual DbSet<CalcTarrifHeaderTbl> CalcTarrifHeaderTbls { get; set; }
        public virtual DbSet<CalcTempratureRegionTbl> CalcTempratureRegionTbls { get; set; }
        public virtual DbSet<TVNNEWForm30View> TVNNEWForm30View { get; set; }
        public virtual DbSet<CalcRgnCityByTrfTempView> CalcRgnCityByTrfTempViews { get; set; }
        public virtual DbSet<TVNF50FormView> TVNF50FormView { get; set; }
        public virtual DbSet<TvnCounterView> TvnCounterViews { get; set; }
        public virtual DbSet<TVNBranchDataView> TVNBranchDataViews { get; set; }
    }
}
